version: "3.9"
services:
    frontend:
        depends_on:
            - db
            - backend
        build:
            context: ../client
            dockerfile: Dockerfile
        ports:
            - 3000:3000

    backend:
        depends_on:
            - db
        environment:
            - MONGODB_URI=db
        build:
            context: ../server
            dockerfile: Dockerfile

    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - "${PWD}/DB/data/db:/data/db"
